---
title: "Noticias Falsas"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Noticias Falsas

En esta p치gina listasmo las noticias falsas que est치n circulando. Si se puede identificar quien las propaga o genera aun mejor. 

### Whatssapp sobre Estado de Emergencia

<blockquote class="twitter-tweet"><p lang="es" dir="ltr">Este mensaje que circula por WhatsApp es falso. <br>Pedimos a la poblaci칩n no dejarse sorprender por informaci칩n an칩nima que circula por medios digitales. 춰Acude siempre a fuentes oficiales!<a href="https://twitter.com/hashtag/Per%C3%BAEst%C3%A1EnNuestrasManos?src=hash&amp;ref_src=twsrc%5Etfw">#Per칰Est치EnNuestrasManos</a> <a href="https://t.co/iGX5cwfzCX">pic.twitter.com/iGX5cwfzCX</a></p>&mdash; MINDEF PERU (@MindefPeru) <a href="https://twitter.com/MindefPeru/status/1240103199433994240?ref_src=twsrc%5Etfw">March 18, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

### Cartilla sobre Estado de Emergencia

<blockquote class="twitter-tweet"><p lang="es" dir="ltr"><a href="https://twitter.com/hashtag/PNPInforma?src=hash&amp;ref_src=twsrc%5Etfw">#PNPInforma</a>游닉| Con relaci칩n a una cartilla que viene circulando por redes sociales, sobre instrucciones para el Estado de Emergencia Nacional, informamos a la opini칩n p칰blica que dicha informaci칩n es falsa. <a href="https://twitter.com/hashtag/FakeNews?src=hash&amp;ref_src=twsrc%5Etfw">#FakeNews</a> <a href="https://twitter.com/hashtag/NoCaigas?src=hash&amp;ref_src=twsrc%5Etfw">#NoCaigas</a> <a href="https://t.co/W9QCarA3DG">pic.twitter.com/W9QCarA3DG</a></p>&mdash; Polic칤a Nacional del Per칰 (@PoliciaPeru) <a href="https://twitter.com/PoliciaPeru/status/1239752286001397762?ref_src=twsrc%5Etfw">March 17, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>




