---
title: "Fuentes OFICIALES"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Fuentes Oficiales

### Página del Gobierno 

[Coronavirus](https://www.gob.pe/coronavirus)

### Página del CDC en español:

[CDC](https://www.cdc.gov/coronavirus/2019-ncov/index-sp.html)

### OMS:

[OMS](https://www.who.int/…/novel-coronavirus-2…/advice-for-public)

### MINSA:
[MINSA-PERU](https://www.gob.pe/…/699-conoce-que-es-el-coronavirus-covid…)

### Ensayos clínicos en humanos
[Organizacion Mundial de la Salud](http://apps.who.int/trialsearch/AdvSearch.aspx?SearchTermStat=117&ReturnUrl=%7e%2fListBy.aspx%3fTypeListing%3d0)
###### 392 estudios sobre diagnóstico, medicamentos y vacunas al 15 de Marzo del 2020.
[Clinical-trials](https://clinicaltrials.gov)


## Legislación especial

### Declaratoria de Emergencia

<blockquote class="twitter-tweet"><p lang="es" dir="ltr">¡Atención! Se publicó el <a href="https://twitter.com/hashtag/DecretoDeUrgencia?src=hash&amp;ref_src=twsrc%5Etfw">#DecretoDeUrgencia</a> que establece diversas medidas excepcionales y temporales para prevenir la propagación del <a href="https://twitter.com/hashtag/Coronavirus?src=hash&amp;ref_src=twsrc%5Etfw">#Coronavirus</a> <a href="https://twitter.com/hashtag/COVID%E3%83%BC19?src=hash&amp;ref_src=twsrc%5Etfw">#COVIDー19</a> en el territorio nacional.<br><br>📄 <a href="https://t.co/oxKEERlzAh">https://t.co/oxKEERlzAh</a><a href="https://twitter.com/hashtag/Per%C3%BAEst%C3%A1EnNuestrasManos?src=hash&amp;ref_src=twsrc%5Etfw">#PerúEstáEnNuestrasManos</a> <a href="https://t.co/tagATe6ohJ">pic.twitter.com/tagATe6ohJ</a></p>&mdash; Consejo de Ministros (@pcmperu) <a href="https://twitter.com/pcmperu/status/1239391233040154625?ref_src=twsrc%5Etfw">March 16, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

### Permisos especiales de transito

[Permiso especial de transito- PERU](https://www.gob.pe/pasedetransito)


### Medidas Económicas

<blockquote class="twitter-tweet"><p lang="es" dir="ltr">Quiero seguir informándoles las medidas para reforzar sistema de vigilancia y respuesta sanitaria frente al COVID-19, así como para reducir el impacto económico en el país. Aprobamos modificaciones presupuestarias por S/498 millones y otras medidas que detallo en este hilo. <br>1/10</p>&mdash; María Antonieta Alva Luperdi (@ToniAlvaL) <a href="https://twitter.com/ToniAlvaL/status/1239407893306380288?ref_src=twsrc%5Etfw">March 16, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


<blockquote class="twitter-tweet"><p lang="es" dir="ltr">Ante el avance del COVID-19 a nivel mundial, venimos trabajando medidas que permitan amortiguar sus efectos sobre la ciudadanía y las mipymes,importantes fuentes de empleo y uno de los motores de nuestra economía. Abro hilo con las acciones recientes. <a href="https://twitter.com/hashtag/Per%C3%BAEst%C3%A1EnNuestrasManos?src=hash&amp;ref_src=twsrc%5Etfw">#PerúEstáEnNuestrasManos</a>.1/7</p>&mdash; María Antonieta Alva Luperdi (@ToniAlvaL) <a href="https://twitter.com/ToniAlvaL/status/1239189178866425856?ref_src=twsrc%5Etfw">March 15, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

