---
title: "Macro Región Centro"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE, message = FALSE)
```

```{r Librerias, echo=FALSE, message=FALSE}
library(tidyverse)
library(rio)
library(sf)
library(ggrepel)
library(ggpubr)
library(cowplot)
library(kableExtra)
data=rio::import("reportes_minsa.xlsx")

source("global.R", encoding = "UTF-8")
```


```{r plot_macro}
data4 = rio::import("reportes_minsa.xlsx", sheet=2)%>%
  dplyr::mutate(
    MACROREG= dplyr::case_when(
        REGION %in% c("TUMBES","PIURA","LAMBAYEQUE","LA LIBERTAD","CAJAMARCA","ANCASH") ~"NORTE",
        REGION %in% c("AMAZONAS","LORETO","UCAYALI","MADRE DE DIOS","SAN MARTIN") ~ "ORIENTE",
        REGION %in% c("ICA","MOQUEGUA","AREQUIPA","TACNA","PUNO","CUSCO") ~ "SUR",
        REGION %in% c("AYACUCHO","APURIMAC","JUNIN", "HUANCAVELICA", "HUANUCO", "PASCO") ~ "CENTRO",
        TRUE ~ "OTRO"),
    Fecha = as.Date(Fecha),
    Positivos=Positivos_totales
  )
```

```{r plot_macro2}
data5 = rio::import("reportes_minsa.xlsx", sheet=2)%>%
  dplyr::mutate(
    MACROREG= dplyr::case_when(
        REGION %in% c("TUMBES","PIURA","LAMBAYEQUE","LA LIBERTAD","CAJAMARCA","ANCASH") ~"NORTE",
        REGION %in% c("AMAZONAS","LORETO","UCAYALI","MADRE DE DIOS","SAN MARTIN") ~ "ORIENTE",
        REGION %in% c("ICA","MOQUEGUA","AREQUIPA","TACNA","PUNO","CUSCO") ~ "SUR",
        REGION %in% c("AYACUCHO","APURIMAC","JUNIN", "HUANCAVELICA", "HUANUCO", "PASCO") ~ "CENTRO",
        TRUE ~ "OTRO"),
    Fecha = as.Date(Fecha),
    Fallecidos=Fallecidos
  )
```


## Tendencias

```{r,panelNORTE1}
plot_macro(data4, "CENTRO")
```

```{r,panelNORTE2}
plot_macro2(data5, "CENTRO")
```


## Información desagregada

**Nota**: Con información de las DIRESAS. No es información completa, estamos tratando de recolectar la información faltante. Puedes acceder a la data completa en el repositorio: https://github.com/jincio/COVID_19_PERU


#### Por Distrito

```{r, eval=FALSE}
#load("./data/provincial_distrital/provincial_distrital.RData")
dd=import("./data/Data_departamental .xlsx", sheet="Ubicacion_casos")

# dd1=dd%>%filter(Fecha==max(dd$Fecha))%>%
#   dplyr::select(Distrito, Valor)
# dd2=import("./data/Data_departamental .xlsx", sheet="Generales")%>%
#   filter(Region==region)
# dd3=import("./data/Data_departamental .xlsx", sheet="Detalles_Fallecidos")%>%filter(Region==region)

```

Aquí te mostramos el número de registros que tenemos por región.

```{r, eval=FALSE}
dd%>%filter(Region%in%c("AYACUCHO","APURIMAC","JUNIN", "HUANCAVELICA", "HUANUCO", "PASCO"))%>%
  dplyr::select(Region,Provincia,Distrito,
                tipo, Valor, Fecha)%>%
  group_by(Region)%>%
  dplyr::summarise(numero_registros=n())%>%
  kable("markdown")
```
